# Generated by Django 5.0.2 on 2024-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="Slug"),
        ),
    ]
