# Generated by Django 5.0.2 on 2024-03-20 15:14

import django.db.models.deletion
import iustia.jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_url",
                    models.URLField(
                        validators=[iustia.jobs.validators.TrustedImageHostValidator()],
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
