# Generated by Django 5.0.2 on 2024-03-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_jobimage_options"),
        ("tags", "0004_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="tags.tag", verbose_name="Tags"
            ),
        ),
    ]
